### PR TITLE
add a way to pass custom http headers without using `Client.headers`

### PR DESCRIPTION
**Pull request by yargevad**

### CODE REVIEW

**Comment by VojtechVitek** [comment]
@yargevad this is great addition, thanks! We also need to use headers so one Client can do requests on behalf of many sub-accounts.

Suggestion: How about passing `net/context` instead of `map[string]string`, though?

```diff
- func (c *Client) HttpPost(url string, data []byte, headers map[string]string) (*Response, error) {
+ func (c *Client) Post(ctx context.Context, url string, body io.Reader) (*Response, error) {
```

## Benefit 1:
We could leave the old `HttpPost()` method for backward compatibility.

```go
func (c *Client) HttpPost(url string, data []byte) (*Response, error) {
  return c.Post(context.Background(), url, bytes.NewReader(data))
}
```

## Benefit 2:
All the `net/context` features for free -- including network timeouts:

```go
sparkpost := gosparkpost.Client()
// c.Init()

// Limit request to 0.5 second.
ctx := context.WithTimeout(ctx, 500*time.Millisecond)
sparkpost.RecipientListCreate(ctx, ...)
```

## Benefit 3:
Instead of letting people set whatever headers they want -- we should rather be explicit and define them using exported consts:

gosparkpost:
```go
type ctxKey int

const (
  SubAccount ctxKey = iota
  SubAccountID
  // ... other options/headers here
)

func (c *Client) DoRequest(ctx context.Context, method, urlStr string, data []byte, headers map[string]string) (*Response, error) {
  // ......
  if subAccount, _ := ctx.Value(SubAccount).(string); subAccount != nil {
     req.Header.Set("X-MSYS-SUBACCOUNT", subAccount.ID)
  }
  if id, _ := ctx.Value(SubAccountID).(string); id != "" {
     req.Header.Set("X-MSYS-SUBACCOUNT", id)
  }
  // ....
}
```

code using gosparkpost:
```go
sparkpost := gosparkpost.Client()
// c.Init()


ctx := context.WithValue(ctx, gosparkpost.SubAccount, "943167809843")
sparkpost.RecipientListCreate(ctx, ...)
```

## Benefit 4:
Since `net/context` will be added to stdlib in Go 1.7, this pkg would be a step ahead and we'd get all the Go 1.7 http benefits for free!

**Comment by yargevad** [comment]
Thanks for the comments and suggestions @VojtechVitek - mostly agreed on 1, 2, 4 although I need to read up a bit.

I'm not sure I understand why you'd prefer not to have the ability to specify arbitrary headers. Could you tell us more about why that's not a good fit for you?

**Comment by VojtechVitek** [comment]
@yargevad what are all arbitrary headers SparkPost API accepts? I could be missing something.

**Comment by yargevad** [comment]
There are only a few now, `Authorization` (api key), `X-MSYS-SUBACCOUNT`, etc. The idea is that if more are added, they can be used w/o library changes.

**Comment by VojtechVitek** [comment]
I see, well, if that's what you like better, we can leave the header as is inside of ctx.

```go
header :=  http.Header{}
header.Set("X-MSYS-SUBACCOUNT", subAccount.ID)
ctx = context.WithValue(ctx, "header", header)
```

```go
func (c *Client) DoRequest(ctx context.Context, method, urlStr string, data []byte, headers map[string]string) (*Response, error) {
  // ......
  if header, ok := ctx.Value("header").(http.Header); ok {
     req.Header = header
  }
  // ....
}
```

**Comment by pxue** [comment]
@yargevad another added benefit of context is that a Deadline and Cancellation signal are carried for free across the API boundaries. For example, if any upstream changes occurred (mail server crashed, user cancellation etc), we have the added benefit of emitting a cancellation signal to the Sparkpost outbound request and cancel it mid-flight.

**Comment by yargevad** [comment]
Closing in favor of [#80](https://github.com/SparkPost/gosparkpost/pull/80) - thanks for all the input!

**Pull request closed without merging**
