### PR TITLE
Adds Initial Open event and EventID

### PR DESCRIPTION
**Pull request by safetysergio**
Background
------------
This pull request adds:
*  `InitialOpen` event in `track.go`
* `EventID` attributes in all the rests of the Webhooks events.

References
-----------
* [Webhooks Events References Guide](https://www.sparkpost.com/docs/tech-resources/webhook-event-reference/#event-types)

### CODE REVIEW

**Comment by yargevad** [comment]
Thanks @safetysergio, @serchavalos - could you work on a fix for that [failing test](https://travis-ci.org/SparkPost/gosparkpost/builds/391104803#L558) please? I'll follow up tomorrow and see if I can fix it (if it's not already taken care of by then).

**Comment by serchavalos** [comment]
@yargevad have you heard from any contributor running into issues like this when running the tests?
```sh
=== RUN   TestTemplateUpdate
2018/06/20 12:48:32 http: panic serving 127.0.0.1:35496: invalid WriteHeader code 0
goroutine 883 [running]:
net/http.(*conn).serve.func1(0xc42024a000)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x76a240, 0xc420044850)
	/usr/local/go/src/runtime/panic.go:502 +0x229
net/http.checkWriteHeaderCode(0x0)
	/usr/local/go/src/net/http/server.go:1070 +0xf3
net/http.(*response).WriteHeader(0xc420166380, 0x0)
	/usr/local/go/src/net/http/server.go:1083 +0x67
github.com/SafetyCulture/gosparkpost_test.mockRestRequestResponseBuilder.func1(0x84d460, 0xc420166380, 0xc42017e100)
	/go/src/github.com/SafetyCulture/gosparkpost/suppression_list_test.go:600 +0xbc
net/http.HandlerFunc.ServeHTTP(0xc420473c70, 0x84d460, 0xc420166380, 0xc42017e100)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4204820c0, 0x84d460, 0xc420166380, 0xc42017e100)
	/usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4202dda00, 0x84d460, 0xc420166380, 0xc42017e100)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc42024a000, 0x84d8a0, 0xc420316380)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
--- FAIL: TestTemplateUpdate (0.01s)
```

**Comment by yargevad** [comment]
That hasn't been reported before, but I see it too (new panic [since go1.10](https://github.com/golang/go/issues/23010). This seems to fix it:

```
--- a/suppression_list_test.go
+++ b/suppression_list_test.go
@@ -597,6 +597,11 @@ func mockRestRequestResponseBuilder(t *testing.T, method string, status int, pat
                if mockResponse != "" {
                        w.Header().Set("Content-Type", "application/json; charset=utf8")
                }
+         if status <= 100 || status >= 600 {
+                 t.Logf("invalid http status code %d", status)
+                 status = 404
+         }
+
                w.WriteHeader(status)
                if mockResponse != "" {
                        w.Write([]byte(mockResponse))
```

**Comment by safetysergio** [comment]
Hey @yargevad. I'm unable to reproduce this broken test locally; I've tried several versions of Go using docker but all of them seem to work fine. I'll come back to it when I get some time

**Pull request closed without merging**
